// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ⚠️ WARNING: DO NOT ADD MIGRATION LOGIC TO THE FRONTEND ⚠️
// 
// This client is for DATA OPERATIONS ONLY (select, insert, update, delete).
// 
// NEVER include code that:
// - Creates or alters tables (CREATE TABLE, ALTER TABLE, DROP TABLE)
// - Creates indexes, functions, or triggers
// - Modifies database schema in any way
// - Calls supabase.rpc() for schema modifications
// - Creates storage buckets (use Supabase Dashboard instead)
//
// All migrations must be run on the BACKEND or through Supabase Dashboard.
// Running migrations from the frontend causes conflicts and errors.

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});