// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
// New env var SUPABASE_ANON_KEY (or NEXT_PUBLIC_SUPABASE_ANON_KEY) takes precedence
// Fallback to legacy VITE_SUPABASE_PUBLISHABLE_KEY or NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
const SUPABASE_PUBLISHABLE_KEY =
  process.env.SUPABASE_ANON_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

const supabaseUrl = SUPABASE_URL ?? '';
const supabaseKey = SUPABASE_PUBLISHABLE_KEY ?? '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ⚠️ WARNING: DO NOT ADD MIGRATION LOGIC TO THE FRONTEND ⚠️
//
// This client is for DATA OPERATIONS ONLY (select, insert, update, delete).
//
// NEVER include code that:
// - Creates or alters tables (CREATE TABLE, ALTER TABLE, DROP TABLE)
// - Creates indexes, functions, or triggers
// - Modifies database schema in any way
// - Calls supabase.rpc() for schema modifications
// - Creates storage buckets (use Supabase Dashboard instead)
//
// All migrations must be run on the BACKEND or through Supabase Dashboard.
// Running migrations from the frontend causes conflicts and errors.

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
